return {
  {
    color = "#6d8086",
    cterm_color = "66",
    icon = "",
    name = "Default",
  },
  [".babelrc"] = {
    color = "#cbcb41",
    cterm_color = "185",
    icon = "",
    name = "Babelrc",
  },
  [".bash_profile"] = {
    color = "#89e051",
    cterm_color = "113",
    icon = "",
    name = "BashProfile",
  },
  [".bashrc"] = {
    color = "#89e051",
    cterm_color = "113",
    icon = "",
    name = "Bashrc",
  },
  [".clang-format"] = {
    color = "#6d8086",
    cterm_color = "66",
    icon = "",
    name = "ClangConfig",
  },
  [".clang-tidy"] = {
    color = "#6d8086",
    cterm_color = "66",
    icon = "",
    name = "ClangConfig",
  },
  [".codespellrc"] = {
    color = "#35DA60",
    cterm_color = "41",
    icon = "󰓆",
    name = "Codespell",
  },
  [".condarc"] = {
    color = "#43b02a",
    cterm_color = "34",
    icon = "",
    name = "Conda",
  },
  [".dockerignore"] = {
    color = "#458ee6",
    cterm_color = "68",
    icon = "󰡨",
    name = "Dockerfile",
  },
  [".ds_store"] = {
    color = "#41535b",
    cterm_color = "239",
    icon = "",
    name = "DsStore",
  },
  [".editorconfig"] = {
    color = "#fff2f2",
    cterm_color = "255",
    icon = "",
    name = "EditorConfig",
  },
  [".env"] = {
    color = "#faf743",
    cterm_color = "227",
    icon = "",
    name = "Env",
  },
  [".eslintignore"] = {
    color = "#4b32c3",
    cterm_color = "56",
    icon = "",
    name = "EslintIgnore",
  },
  [".eslintrc"] = {
    color = "#4b32c3",
    cterm_color = "56",
    icon = "",
    name = "Eslintrc",
  },
  [".git-blame-ignore-revs"] = {
    color = "#f54d27",
    cterm_color = "196",
    icon = "",
    name = "GitBlameIgnore",
  },
  [".gitattributes"] = {
    color = "#f54d27",
    cterm_color = "196",
    icon = "",
    name = "GitAttributes",
  },
  [".gitconfig"] = {
    color = "#f54d27",
    cterm_color = "196",
    icon = "",
    name = "GitConfig",
  },
  [".gitignore"] = {
    icon = "",
    color = "#428850",
    name = "GitIgnore",
  },
  [".gitlab-ci.yml"] = {
    color = "#e24329",
    cterm_color = "196",
    icon = "",
    name = "GitlabCI",
  },
  [".gitmodules"] = {
    color = "#f54d27",
    cterm_color = "196",
    icon = "",
    name = "GitModules",
  },
  [".gtkrc-2.0"] = {
    color = "#ffffff",
    cterm_color = "231",
    icon = "",
    name = "GTK",
  },
  [".gvimrc"] = {
    color = "#019833",
    cterm_color = "28",
    icon = "",
    name = "Gvimrc",
  },
  [".justfile"] = {
    color = "#6d8086",
    cterm_color = "66",
    icon = "",
    name = "Justfile",
  },
  [".luacheckrc"] = {
    color = "#00a2ff",
    cterm_color = "75",
    icon = "",
    name = "Luaurc",
  },
  [".luaurc"] = {
    color = "#00a2ff",
    cterm_color = "75",
    icon = "",
    name = "Luaurc",
  },
  [".mailmap"] = {
    color = "#f54d27",
    cterm_color = "196",
    icon = "󰊢",
    name = "Mailmap",
  },
  [".nanorc"] = {
    color = "#440077",
    cterm_color = "54",
    icon = "",
    name = "Nano",
  },
  [".npmignore"] = {
    color = "#E8274B",
    cterm_color = "197",
    icon = "",
    name = "NPMIgnore",
  },
  [".npmrc"] = {
    color = "#E8274B",
    cterm_color = "197",
    icon = "",
    name = "NPMrc",
  },
  [".nuxtrc"] = {
    color = "#00c58e",
    cterm_color = "42",
    icon = "󱄆",
    name = "NuxtConfig",
  },
  [".nvmrc"] = {
    color = "#5FA04E",
    cterm_color = "71",
    icon = "",
    name = "node",
  },
  [".pre-commit-config.yaml"] = {
    color = "#F8B424",
    cterm_color = "214",
    icon = "󰛢",
    name = "PreCommitConfig",
  },
  [".prettierignore"] = {
    color = "#4285F4",
    cterm_color = "33",
    icon = "",
    name = "PrettierIgnore",
  },
  [".prettierrc"] = {
    color = "#4285F4",
    cterm_color = "33",
    icon = "",
    name = "PrettierConfig",
  },
  [".prettierrc.cjs"] = {
    color = "#4285F4",
    cterm_color = "33",
    icon = "",
    name = "PrettierConfig",
  },
  [".prettierrc.js"] = {
    color = "#4285F4",
    cterm_color = "33",
    icon = "",
    name = "PrettierConfig",
  },
  [".prettierrc.json"] = {
    color = "#4285F4",
    cterm_color = "33",
    icon = "",
    name = "PrettierConfig",
  },
  [".prettierrc.json5"] = {
    color = "#4285F4",
    cterm_color = "33",
    icon = "",
    name = "PrettierConfig",
  },
  [".prettierrc.mjs"] = {
    color = "#4285F4",
    cterm_color = "33",
    icon = "",
    name = "PrettierConfig",
  },
  [".prettierrc.toml"] = {
    color = "#4285F4",
    cterm_color = "33",
    icon = "",
    name = "PrettierConfig",
  },
  [".prettierrc.yaml"] = {
    color = "#4285F4",
    cterm_color = "33",
    icon = "",
    name = "PrettierConfig",
  },
  [".prettierrc.yml"] = {
    color = "#4285F4",
    cterm_color = "33",
    icon = "",
    name = "PrettierConfig",
  },
  [".pylintrc"] = {
    color = "#6d8086",
    cterm_color = "66",
    icon = "",
    name = "PyLintConfig",
  },
  [".settings.json"] = {
    color = "#854CC7",
    cterm_color = "98",
    icon = "",
    name = "SettingsJson",
  },
  [".srcinfo"] = {
    color = "#0f94d2",
    cterm_color = "67",
    icon = "󰣇",
    name = "SRCINFO",
  },
  [".vimrc"] = {
    color = "#019833",
    cterm_color = "28",
    icon = "",
    name = "Vimrc",
  },
  [".xauthority"] = {
    color = "#e54d18",
    cterm_color = "196",
    icon = "",
    name = "Xauthority",
  },
  [".xinitrc"] = {
    color = "#e54d18",
    cterm_color = "196",
    icon = "",
    name = "XInitrc",
  },
  [".xresources"] = {
    color = "#e54d18",
    cterm_color = "196",
    icon = "",
    name = "Xresources",
  },
  [".xsession"] = {
    color = "#e54d18",
    cterm_color = "196",
    icon = "",
    name = "Xsession",
  },
  [".zprofile"] = {
    color = "#89e051",
    cterm_color = "113",
    icon = "",
    name = "Zshprofile",
  },
  [".zshenv"] = {
    color = "#89e051",
    cterm_color = "113",
    icon = "",
    name = "Zshenv",
  },
  [".zshrc"] = {
    color = "#89e051",
    cterm_color = "113",
    icon = "",
    name = "Zshrc",
  },
  ["3gp"] = {
    color = "#FD971F",
    cterm_color = "208",
    icon = "",
    name = "3gp",
  },
  ["3mf"] = {
    color = "#888888",
    cterm_color = "102",
    icon = "󰆧",
    name = "3DObjectFile",
  },
  ["7z"] = {
    color = "#eca517",
    cterm_color = "214",
    icon = "",
    name = "7z",
  },
  Dockerfile = {
    color = "#458ee6",
    cterm_color = "68",
    icon = "󰡨",
    name = "Dockerfile",
  },
  R = {
    color = "#2266ba",
    cterm_color = "25",
    icon = "󰟔",
    name = "R",
  },
  _gvimrc = {
    color = "#019833",
    cterm_color = "28",
    icon = "",
    name = "Gvimrc",
  },
  _vimrc = {
    color = "#019833",
    cterm_color = "28",
    icon = "",
    name = "Vimrc",
  },
  a = {
    color = "#dcddd6",
    cterm_color = "253",
    icon = "",
    name = "StaticLibraryArchive",
  },
  aac = {
    color = "#00afff",
    cterm_color = "39",
    icon = "",
    name = "AdvancedAudioCoding",
  },
  adb = {
    color = "#22ffff",
    cterm_color = "51",
    icon = "",
    name = "AdaBody",
  },
  ads = {
    color = "#ffffff",
    cterm_color = "231",
    icon = "",
    name = "AdaSpecification",
  },
  ai = {
    color = "#cbcb41",
    cterm_color = "185",
    icon = "",
    name = "Ai",
  },
  aif = {
    color = "#00afff",
    cterm_color = "39",
    icon = "",
    name = "AudioInterchangeFileFormat",
  },
  aiff = {
    color = "#00afff",
    cterm_color = "39",
    icon = "",
    name = "AudioInterchangeFileFormat",
  },
  alma = {
    color = "#ff4649",
    cterm_color = "203",
    icon = "",
    name = "Almalinux",
  },
  alpine = {
    color = "#0d597f",
    cterm_color = "24",
    icon = "",
    name = "Alpine",
  },
  android = {
    color = "#34a853",
    cterm_color = "35",
    icon = "",
    name = "Android",
  },
  aosc = {
    color = "#c00000",
    cterm_color = "124",
    icon = "",
    name = "AOSC",
  },
  ape = {
    color = "#00afff",
    cterm_color = "39",
    icon = "",
    name = "MonkeysAudio",
  },
  apk = {
    color = "#34a853",
    cterm_color = "35",
    icon = "",
    name = "apk",
  },
  apl = {
    color = "#24a148",
    cterm_color = "35",
    icon = "",
    name = "APL",
  },
  app = {
    color = "#9F0500",
    cterm_color = "124",
    icon = "",
    name = "App",
  },
  apple = {
    color = "#A2AAAD",
    cterm_color = "248",
    icon = "",
    name = "Apple",
  },
  applescript = {
    color = "#6d8085",
    cterm_color = "66",
    icon = "",
    name = "AppleScript",
  },
  arch = {
    color = "#0f94d2",
    cterm_color = "67",
    icon = "󰣇",
    name = "Arch",
  },
  archcraft = {
    color = "#86bba3",
    cterm_color = "108",
    icon = "",
    name = "Archcraft",
  },
  archlabs = {
    color = "#503f42",
    cterm_color = "238",
    icon = "",
    name = "Archlabs",
  },
  arcolinux = {
    color = "#6690eb",
    cterm_color = "68",
    icon = "",
    name = "ArcoLinux",
  },
  artix = {
    color = "#41b4d7",
    cterm_color = "38",
    icon = "",
    name = "Artix",
  },
  asc = {
    color = "#576d7f",
    cterm_color = "242",
    icon = "󰦝",
    name = "Asc",
  },
  asm = {
    color = "#0091BD",
    cterm_color = "31",
    icon = "",
    name = "ASM",
  },
  ass = {
    color = "#ffb713",
    cterm_color = "214",
    icon = "󰨖",
    name = "Ass",
  },
  astro = {
    color = "#e23f67",
    cterm_color = "197",
    icon = "",
    name = "Astro",
  },
  authors = {
    color = "#A172FF",
    cterm_color = "135",
    icon = "",
    name = "AUTHORS",
  },
  ["authors.txt"] = {
    color = "#A172FF",
    cterm_color = "135",
    icon = "",
    name = "AUTHORS",
  },
  avif = {
    color = "#a074c4",
    cterm_color = "140",
    icon = "",
    name = "Avif",
  },
  awesomewm = {
    color = "#535d6c",
    cterm_color = "59",
    icon = "",
    name = "awesome",
  },
  awk = {
    color = "#4d5a5e",
    cterm_color = "240",
    icon = "",
    name = "Awk",
  },
  azcli = {
    color = "#0078d4",
    cterm_color = "32",
    icon = "",
    name = "AzureCli",
  },
  bak = {
    color = "#6d8086",
    cterm_color = "66",
    icon = "󰁯",
    name = "Backup",
  },
  bash = {
    color = "#89e051",
    cterm_color = "113",
    icon = "",
    name = "Bash",
  },
  bat = {
    color = "#C1F12E",
    cterm_color = "191",
    icon = "",
    name = "Bat",
  },
  bazel = {
    color = "#89e051",
    cterm_color = "113",
    icon = "",
    name = "Bazel",
  },
  bib = {
    color = "#cbcb41",
    cterm_color = "185",
    icon = "󱉟",
    name = "BibTeX",
  },
  bicep = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "Bicep",
  },
  bicepparam = {
    color = "#9f74b3",
    cterm_color = "133",
    icon = "",
    name = "BicepParameters",
  },
  biglinux = {
    color = "#189fc8",
    cterm_color = "38",
    icon = "",
    name = "BigLinux",
  },
  bin = {
    color = "#9F0500",
    cterm_color = "124",
    icon = "",
    name = "Bin",
  },
  ["blade.php"] = {
    color = "#f05340",
    cterm_color = "203",
    icon = "",
    name = "Blade",
  },
  blend = {
    color = "#ea7600",
    cterm_color = "208",
    icon = "󰂫",
    name = "Blender",
  },
  blp = {
    color = "#5796E2",
    cterm_color = "68",
    icon = "󰺾",
    name = "Blueprint",
  },
  bmp = {
    color = "#a074c4",
    cterm_color = "140",
    icon = "",
    name = "Bmp",
  },
  bqn = {
    color = "#24a148",
    cterm_color = "35",
    icon = "",
    name = "APL",
  },
  brep = {
    color = "#839463",
    cterm_color = "101",
    icon = "󰻫",
    name = "BoundaryRepresentation",
  },
  brewfile = {
    color = "#701516",
    cterm_color = "52",
    icon = "",
    name = "Brewfile",
  },
  bspwm = {
    color = "#4f4f4f",
    cterm_color = "239",
    icon = "",
    name = "BSPWM",
  },
  bspwmrc = {
    color = "#2f2f2f",
    cterm_color = "236",
    icon = "",
    name = "BSPWM",
  },
  budgie = {
    color = "#4e5361",
    cterm_color = "240",
    icon = "",
    name = "Budgie",
  },
  build = {
    color = "#89e051",
    cterm_color = "113",
    icon = "",
    name = "BazelBuild",
  },
  ["build.gradle"] = {
    color = "#005f87",
    cterm_color = "24",
    icon = "",
    name = "GradleBuildScript",
  },
  ["build.zig.zon"] = {
    color = "#f69a1b",
    cterm_color = "172",
    icon = "",
    name = "ZigObjectNotation",
  },
  ["bun.lockb"] = {
    color = "#eadcd1",
    cterm_color = "253",
    icon = "",
    name = "BunLockfile",
  },
  bz = {
    color = "#eca517",
    cterm_color = "214",
    icon = "",
    name = "Bz",
  },
  bz2 = {
    color = "#eca517",
    cterm_color = "214",
    icon = "",
    name = "Bz2",
  },
  bz3 = {
    color = "#eca517",
    cterm_color = "214",
    icon = "",
    name = "Bz3",
  },
  bzl = {
    color = "#89e051",
    cterm_color = "113",
    icon = "",
    name = "Bzl",
  },
  c = {
    color = "#599eff",
    cterm_color = "111",
    icon = "",
    name = "C",
  },
  ["c++"] = {
    color = "#f34b7d",
    cterm_color = "204",
    icon = "",
    name = "CPlusPlus",
  },
  cache = {
    color = "#ffffff",
    cterm_color = "231",
    icon = "",
    name = "Cache",
  },
  cantorrc = {
    color = "#1c99f3",
    cterm_color = "32",
    icon = "",
    name = "Cantorrc",
  },
  cast = {
    color = "#FD971F",
    cterm_color = "208",
    icon = "",
    name = "Asciinema",
  },
  cbl = {
    color = "#005ca5",
    cterm_color = "25",
    icon = "",
    name = "Cobol",
  },
  cc = {
    color = "#f34b7d",
    cterm_color = "204",
    icon = "",
    name = "CPlusPlus",
  },
  ccm = {
    color = "#f34b7d",
    cterm_color = "204",
    icon = "",
    name = "CPlusPlusModule",
  },
  centos = {
    color = "#a2518d",
    cterm_color = "132",
    icon = "",
    name = "Centos",
  },
  cfg = {
    color = "#6d8086",
    cterm_color = "66",
    icon = "",
    name = "Configuration",
  },
  checkhealth = {
    color = "#75B4FB",
    cterm_color = "75",
    icon = "󰓙",
    name = "Checkhealth",
  },
  cinnamon = {
    color = "#dc682e",
    cterm_color = "166",
    icon = "",
    name = "Cinnamon",
  },
  cjs = {
    color = "#cbcb41",
    cterm_color = "185",
    icon = "",
    name = "Cjs",
  },
  clj = {
    color = "#8dc149",
    cterm_color = "113",
    icon = "",
    name = "Clojure",
  },
  cljc = {
    color = "#8dc149",
    cterm_color = "113",
    icon = "",
    name = "ClojureC",
  },
  cljd = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "ClojureDart",
  },
  cljs = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "ClojureJS",
  },
  cmake = {
    color = "#dce3eb",
    cterm_color = "254",
    icon = "",
    name = "CMake",
  },
  ["cmakelists.txt"] = {
    color = "#dce3eb",
    cterm_color = "254",
    icon = "",
    name = "CMakeLists",
  },
  cob = {
    color = "#005ca5",
    cterm_color = "25",
    icon = "",
    name = "Cobol",
  },
  cobol = {
    color = "#005ca5",
    cterm_color = "25",
    icon = "",
    name = "Cobol",
  },
  code_of_conduct = {
    color = "#E41662",
    cterm_color = "161",
    icon = "",
    name = "CodeOfConduct",
  },
  ["code_of_conduct.md"] = {
    color = "#E41662",
    cterm_color = "161",
    icon = "",
    name = "CodeOfConduct",
  },
  coffee = {
    color = "#cbcb41",
    cterm_color = "185",
    icon = "",
    name = "Coffee",
  },
  commit_editmsg = {
    color = "#f54d27",
    cterm_color = "196",
    icon = "",
    name = "GitCommit",
  },
  ["commitlint.config.js"] = {
    color = "#2b9689",
    cterm_color = "30",
    icon = "󰜘",
    name = "CommitlintConfig",
  },
  ["commitlint.config.ts"] = {
    color = "#2b9689",
    cterm_color = "30",
    icon = "󰜘",
    name = "CommitlintConfig",
  },
  ["compose.yaml"] = {
    color = "#458ee6",
    cterm_color = "68",
    icon = "󰡨",
    name = "Dockerfile",
  },
  ["compose.yml"] = {
    color = "#458ee6",
    cterm_color = "68",
    icon = "󰡨",
    name = "Dockerfile",
  },
  conda = {
    color = "#43b02a",
    cterm_color = "34",
    icon = "",
    name = "Conda",
  },
  conf = {
    color = "#6d8086",
    cterm_color = "66",
    icon = "",
    name = "Conf",
  },
  config = {
    color = "#6d8086",
    cterm_color = "66",
    icon = "",
    name = "Config",
  },
  ["config.ru"] = {
    color = "#701516",
    cterm_color = "52",
    icon = "",
    name = "ConfigRu",
  },
  containerfile = {
    color = "#458ee6",
    cterm_color = "68",
    icon = "󰡨",
    name = "Dockerfile",
  },
  copying = {
    color = "#cbcb41",
    cterm_color = "185",
    icon = "",
    name = "License",
  },
  ["copying.lesser"] = {
    color = "#cbcb41",
    cterm_color = "185",
    icon = "",
    name = "License",
  },
  cow = {
    color = "#965824",
    cterm_color = "130",
    icon = "󰆚",
    name = "CowsayFile",
  },
  cp = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "Cp",
  },
  cpp = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "Cpp",
  },
  cppm = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "Cppm",
  },
  cpy = {
    color = "#005ca5",
    cterm_color = "25",
    icon = "",
    name = "Cobol",
  },
  cr = {
    color = "#c8c8c8",
    cterm_color = "251",
    icon = "",
    name = "Crystal",
  },
  crdownload = {
    color = "#44cda8",
    cterm_color = "43",
    icon = "",
    name = "Crdownload",
  },
  crystallinux = {
    color = "#a900ff",
    cterm_color = "129",
    icon = "",
    name = "CrystalLinux",
  },
  cs = {
    color = "#596706",
    cterm_color = "58",
    icon = "󰌛",
    name = "Cs",
  },
  csh = {
    color = "#4d5a5e",
    cterm_color = "240",
    icon = "",
    name = "Csh",
  },
  cshtml = {
    color = "#512bd4",
    cterm_color = "56",
    icon = "󱦗",
    name = "RazorPage",
  },
  cson = {
    color = "#cbcb41",
    cterm_color = "185",
    icon = "",
    name = "Cson",
  },
  csproj = {
    color = "#512bd4",
    cterm_color = "56",
    icon = "󰪮",
    name = "CSharpProject",
  },
  css = {
    color = "#42a5f5",
    cterm_color = "75",
    icon = "",
    name = "Css",
  },
  csv = {
    color = "#89e051",
    cterm_color = "113",
    icon = "",
    name = "Csv",
  },
  cts = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "Cts",
  },
  cu = {
    color = "#89e051",
    cterm_color = "113",
    icon = "",
    name = "cuda",
  },
  cue = {
    color = "#ed95ae",
    cterm_color = "211",
    icon = "󰲹",
    name = "Cue",
  },
  cuh = {
    color = "#a074c4",
    cterm_color = "140",
    icon = "",
    name = "cudah",
  },
  cxx = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "Cxx",
  },
  cxxm = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "Cxxm",
  },
  d = {
    color = "#b03931",
    cterm_color = "124",
    icon = "",
    name = "D",
  },
  ["d.ts"] = {
    color = "#d59855",
    cterm_color = "172",
    icon = "",
    name = "TypeScriptDeclaration",
  },
  dart = {
    color = "#03589C",
    cterm_color = "25",
    icon = "",
    name = "Dart",
  },
  db = {
    color = "#dad8d8",
    cterm_color = "188",
    icon = "",
    name = "Db",
  },
  dconf = {
    color = "#ffffff",
    cterm_color = "231",
    icon = "",
    name = "Dconf",
  },
  debian = {
    color = "#a80030",
    cterm_color = "88",
    icon = "",
    name = "Debian",
  },
  deepin = {
    color = "#2ca7f8",
    cterm_color = "39",
    icon = "",
    name = "Deepin",
  },
  desktop = {
    color = "#563d7c",
    cterm_color = "54",
    icon = "",
    name = "DesktopEntry",
  },
  devuan = {
    color = "#404a52",
    cterm_color = "238",
    icon = "",
    name = "Devuan",
  },
  diff = {
    color = "#41535b",
    cterm_color = "239",
    icon = "",
    name = "Diff",
  },
  dll = {
    color = "#4d2c0b",
    cterm_color = "52",
    icon = "",
    name = "Dll",
  },
  doc = {
    color = "#185abd",
    cterm_color = "26",
    icon = "󰈬",
    name = "Doc",
  },
  ["docker-compose.dev.yaml"] = {
    color = "#458ee6",
    cterm_color = "68",
    icon = "󰡨",
    name = "Dockerfile",
  },
  ["docker-compose.dev.yml"] = {
    color = "#458ee6",
    cterm_color = "68",
    icon = "󰡨",
    name = "Dockerfile",
  },
  ["docker-compose.yaml"] = {
    color = "#458ee6",
    cterm_color = "68",
    icon = "󰡨",
    name = "Dockerfile",
  },
  ["docker-compose.yml"] = {
    color = "#458ee6",
    cterm_color = "68",
    icon = "󰡨",
    name = "Dockerfile",
  },
  ["dockerfile.backend.dev"] = {
    color = "#458ee6",
    cterm_color = "68",
    icon = "󰡨",
    name = "Dockerfile",
  },
  ["dockerfile.backend"] = {
    color = "#458ee6",
    cterm_color = "68",
    icon = "󰡨",
    name = "Dockerfile",
  },
  dockerfile = {
    color = "#458ee6",
    cterm_color = "68",
    icon = "󰡨",
    name = "Dockerfile",
  },
  docx = {
    color = "#185abd",
    cterm_color = "26",
    icon = "󰈬",
    name = "Docx",
  },
  dot = {
    color = "#30638e",
    cterm_color = "24",
    icon = "󱁉",
    name = "Dot",
  },
  download = {
    color = "#44cda8",
    cterm_color = "43",
    icon = "",
    name = "Download",
  },
  drl = {
    color = "#ffafaf",
    cterm_color = "217",
    icon = "",
    name = "Drools",
  },
  dropbox = {
    color = "#0061FE",
    cterm_color = "27",
    icon = "",
    name = "Dropbox",
  },
  dump = {
    color = "#dad8d8",
    cterm_color = "188",
    icon = "",
    name = "Dump",
  },
  dwg = {
    color = "#839463",
    cterm_color = "101",
    icon = "󰻫",
    name = "AutoCADDwg",
  },
  dwm = {
    color = "#1177aa",
    cterm_color = "31",
    icon = "",
    name = "dwm",
  },
  dxf = {
    color = "#839463",
    cterm_color = "101",
    icon = "󰻫",
    name = "AutoCADDxf",
  },
  ebook = {
    color = "#eab16d",
    cterm_color = "215",
    icon = "",
    name = "Ebook",
  },
  ebuild = {
    color = "#4C416E",
    cterm_color = "60",
    icon = "",
    name = "GentooBuild",
  },
  edn = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "Edn",
  },
  eex = {
    color = "#a074c4",
    cterm_color = "140",
    icon = "",
    name = "Eex",
  },
  ejs = {
    color = "#cbcb41",
    cterm_color = "185",
    icon = "",
    name = "Ejs",
  },
  el = {
    color = "#8172be",
    cterm_color = "97",
    icon = "",
    name = "Elisp",
  },
  elc = {
    color = "#8172be",
    cterm_color = "97",
    icon = "",
    name = "Elisp",
  },
  elementary = {
    color = "#5890c2",
    cterm_color = "67",
    icon = "",
    name = "Elementary",
  },
  elf = {
    color = "#9F0500",
    cterm_color = "124",
    icon = "",
    name = "Elf",
  },
  elm = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "Elm",
  },
  eln = {
    color = "#8172be",
    cterm_color = "97",
    icon = "",
    name = "Elisp",
  },
  endeavour = {
    color = "#7b3db9",
    cterm_color = "91",
    icon = "",
    name = "Endeavour",
  },
  enlightenment = {
    color = "#ffffff",
    cterm_color = "231",
    icon = "",
    name = "Enlightenment",
  },
  env = {
    color = "#faf743",
    cterm_color = "227",
    icon = "",
    name = "Env",
  },
  eot = {
    color = "#ECECEC",
    cterm_color = "255",
    icon = "",
    name = "EmbeddedOpenTypeFont",
  },
  epp = {
    color = "#FFA61A",
    cterm_color = "214",
    icon = "",
    name = "Epp",
  },
  epub = {
    color = "#eab16d",
    cterm_color = "215",
    icon = "",
    name = "Epub",
  },
  erb = {
    color = "#701516",
    cterm_color = "52",
    icon = "",
    name = "Erb",
  },
  erl = {
    color = "#B83998",
    cterm_color = "163",
    icon = "",
    name = "Erl",
  },
  ["eslint.config.cjs"] = {
    color = "#4b32c3",
    cterm_color = "56",
    icon = "",
    name = "Eslintrc",
  },
  ["eslint.config.js"] = {
    color = "#4b32c3",
    cterm_color = "56",
    icon = "",
    name = "Eslintrc",
  },
  ["eslint.config.mjs"] = {
    color = "#4b32c3",
    cterm_color = "56",
    icon = "",
    name = "Eslintrc",
  },
  ["eslint.config.ts"] = {
    color = "#4b32c3",
    cterm_color = "56",
    icon = "",
    name = "Eslintrc",
  },
  ex = {
    color = "#a074c4",
    cterm_color = "140",
    icon = "",
    name = "Ex",
  },
  exe = {
    color = "#9F0500",
    cterm_color = "124",
    icon = "",
    name = "Exe",
  },
  exs = {
    color = "#a074c4",
    cterm_color = "140",
    icon = "",
    name = "Exs",
  },
  ["ext_typoscript_setup.txt"] = {
    color = "#FF8700",
    cterm_color = "208",
    icon = "",
    name = "TypoScriptSetup",
  },
  ["f#"] = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "Fsharp",
  },
  f3d = {
    color = "#839463",
    cterm_color = "101",
    icon = "󰻫",
    name = "Fusion360",
  },
  f90 = {
    color = "#734f96",
    cterm_color = "97",
    icon = "󱈚",
    name = "Fortran",
  },
  ["favicon.ico"] = {
    color = "#cbcb41",
    cterm_color = "185",
    icon = "",
    name = "Favicon",
  },
  fbx = {
    color = "#888888",
    cterm_color = "102",
    icon = "󰆧",
    name = "3DObjectFile",
  },
  fcbak = {
    color = "#cb333b",
    cterm_color = "160",
    icon = "",
    name = "FreeCAD",
  },
  fcmacro = {
    color = "#cb333b",
    cterm_color = "160",
    icon = "",
    name = "FreeCAD",
  },
  fcmat = {
    color = "#cb333b",
    cterm_color = "160",
    icon = "",
    name = "FreeCAD",
  },
  fcparam = {
    color = "#cb333b",
    cterm_color = "160",
    icon = "",
    name = "FreeCAD",
  },
  fcscript = {
    color = "#cb333b",
    cterm_color = "160",
    icon = "",
    name = "FreeCAD",
  },
  fcstd = {
    color = "#cb333b",
    cterm_color = "160",
    icon = "",
    name = "FreeCAD",
  },
  fcstd1 = {
    color = "#cb333b",
    cterm_color = "160",
    icon = "",
    name = "FreeCAD",
  },
  fctb = {
    color = "#cb333b",
    cterm_color = "160",
    icon = "",
    name = "FreeCAD",
  },
  fctl = {
    color = "#cb333b",
    cterm_color = "160",
    icon = "",
    name = "FreeCAD",
  },
  fdmdownload = {
    color = "#44cda8",
    cterm_color = "43",
    icon = "",
    name = "Fdmdownload",
  },
  fedora = {
    color = "#072a5e",
    cterm_color = "17",
    icon = "",
    name = "Fedora",
  },
  fish = {
    color = "#4d5a5e",
    cterm_color = "240",
    icon = "",
    name = "Fish",
  },
  flac = {
    color = "#0075aa",
    cterm_color = "24",
    icon = "",
    name = "FreeLosslessAudioCodec",
  },
  flc = {
    color = "#ECECEC",
    cterm_color = "255",
    icon = "",
    name = "FIGletFontControl",
  },
  flf = {
    color = "#ECECEC",
    cterm_color = "255",
    icon = "",
    name = "FIGletFontFormat",
  },
  fluxbox = {
    color = "#555555",
    cterm_color = "240",
    icon = "",
    name = "Fluxbox",
  },
  fnl = {
    color = "#fff3d7",
    cterm_color = "230",
    icon = "",
    name = "Fennel",
  },
  fodg = {
    color = "#FFFB57",
    cterm_color = "227",
    icon = "",
    name = "LibreOfficeGraphics",
  },
  fodp = {
    color = "#FE9C45",
    cterm_color = "215",
    icon = "",
    name = "LibreOfficeImpress",
  },
  fods = {
    color = "#78FC4E",
    cterm_color = "119",
    icon = "",
    name = "LibreOfficeCalc",
  },
  fodt = {
    color = "#2DCBFD",
    cterm_color = "81",
    icon = "",
    name = "LibreOfficeWriter",
  },
  ["fp-info-cache"] = {
    color = "#ffffff",
    cterm_color = "231",
    icon = "",
    name = "KiCadCache",
  },
  ["fp-lib-table"] = {
    color = "#ffffff",
    cterm_color = "231",
    icon = "",
    name = "KiCadFootprintTable",
  },
  freebsd = {
    color = "#c90f02",
    cterm_color = "160",
    icon = "",
    name = "FreeBSD",
  },
  ["freecad.conf"] = {
    color = "#CB333B",
    cterm_color = "160",
    icon = "",
    name = "FreeCADConfig",
  },
  fs = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "Fs",
  },
  fsi = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "Fsi",
  },
  fsscript = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "Fsscript",
  },
  fsx = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "Fsx",
  },
  garuda = {
    color = "#2974e1",
    cterm_color = "33",
    icon = "",
    name = "GarudaLinux",
  },
  gcode = {
    color = "#1471ad",
    cterm_color = "32",
    icon = "󰐫",
    name = "GCode",
  },
  gd = {
    color = "#6d8086",
    cterm_color = "66",
    icon = "",
    name = "GDScript",
  },
  gemfile = {
    color = "#701516",
    cterm_color = "52",
    icon = "",
    name = "Gemfile",
  },
  gemspec = {
    color = "#701516",
    cterm_color = "52",
    icon = "",
    name = "Gemspec",
  },
  gentoo = {
    color = "#b1abce",
    cterm_color = "146",
    icon = "󰣨",
    name = "Gentoo",
  },
  gif = {
    color = "#a074c4",
    cterm_color = "140",
    icon = "",
    name = "Gif",
  },
  git = {
    color = "#F14C28",
    cterm_color = "196",
    icon = "",
    name = "GitLogo",
  },
  glb = {
    color = "#FFB13B",
    cterm_color = "214",
    icon = "",
    name = "BinaryGLTF",
  },
  gleam = {
    color = "#ffaff3",
    cterm_color = "219",
    icon = "",
    name = "Gleam",
  },
  gnome = {
    color = "#ffffff",
    cterm_color = "231",
    icon = "",
    name = "GNOME",
  },
  gnumakefile = {
    color = "#6d8086",
    cterm_color = "66",
    icon = "",
    name = "Makefile",
  },
  go = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "Go",
  },
  ["go.mod"] = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "GoMod",
  },
  ["go.sum"] = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "GoSum",
  },
  ["go.work"] = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "GoWork",
  },
  godot = {
    color = "#6d8086",
    cterm_color = "66",
    icon = "",
    name = "GodotProject",
  },
  gpr = {
    color = "#FF33FF",
    cterm_color = "201",
    icon = "",
    name = "GPRBuildProject",
  },
  gql = {
    color = "#e535ab",
    cterm_color = "199",
    icon = "",
    name = "GraphQL",
  },
  gradle = {
    color = "#005f87",
    cterm_color = "24",
    icon = "",
    name = "Gradle",
  },
  ["gradle-wrapper.properties"] = {
    color = "#005f87",
    cterm_color = "24",
    icon = "",
    name = "GradleWrapperProperties",
  },
  ["gradle.properties"] = {
    color = "#005f87",
    cterm_color = "24",
    icon = "",
    name = "GradleProperties",
  },
  gradlew = {
    color = "#005f87",
    cterm_color = "24",
    icon = "",
    name = "GradleWrapperScript",
  },
  graphql = {
    color = "#e535ab",
    cterm_color = "199",
    icon = "",
    name = "GraphQL",
  },
  gresource = {
    color = "#ffffff",
    cterm_color = "231",
    icon = "",
    name = "GTK",
  },
  groovy = {
    color = "#4a687c",
    cterm_color = "24",
    icon = "",
    name = "Groovy",
  },
  ["gruntfile.babel.js"] = {
    color = "#e37933",
    cterm_color = "166",
    icon = "",
    name = "Gruntfile",
  },
  ["gruntfile.coffee"] = {
    color = "#e37933",
    cterm_color = "166",
    icon = "",
    name = "Gruntfile",
  },
  ["gruntfile.js"] = {
    color = "#e37933",
    cterm_color = "166",
    icon = "",
    name = "Gruntfile",
  },
  ["gruntfile.ts"] = {
    color = "#e37933",
    cterm_color = "166",
    icon = "",
    name = "Gruntfile",
  },
  gtkrc = {
    color = "#ffffff",
    cterm_color = "231",
    icon = "",
    name = "GTK",
  },
  guix = {
    color = "#ffcc00",
    cterm_color = "220",
    icon = "",
    name = "Guix",
  },
  ["gulpfile.babel.js"] = {
    color = "#cc3e44",
    cterm_color = "167",
    icon = "",
    name = "Gulpfile",
  },
  ["gulpfile.coffee"] = {
    color = "#cc3e44",
    cterm_color = "167",
    icon = "",
    name = "Gulpfile",
  },
  ["gulpfile.js"] = {
    color = "#cc3e44",
    cterm_color = "167",
    icon = "",
    name = "Gulpfile",
  },
  ["gulpfile.ts"] = {
    color = "#cc3e44",
    cterm_color = "167",
    icon = "",
    name = "Gulpfile",
  },
  gv = {
    color = "#30638e",
    cterm_color = "24",
    icon = "󱁉",
    name = "Gv",
  },
  gz = {
    color = "#eca517",
    cterm_color = "214",
    icon = "",
    name = "Gz",
  },
  h = {
    color = "#a074c4",
    cterm_color = "140",
    icon = "",
    name = "H",
  },
  haml = {
    color = "#eaeae1",
    cterm_color = "255",
    icon = "",
    name = "Haml",
  },
  hbs = {
    color = "#f0772b",
    cterm_color = "202",
    icon = "",
    name = "Hbs",
  },
  heex = {
    color = "#a074c4",
    cterm_color = "140",
    icon = "",
    name = "Heex",
  },
  hex = {
    color = "#2e63ff",
    cterm_color = "27",
    icon = "",
    name = "Hexadecimal",
  },
  hh = {
    color = "#a074c4",
    cterm_color = "140",
    icon = "",
    name = "Hh",
  },
  hpp = {
    color = "#a074c4",
    cterm_color = "140",
    icon = "",
    name = "Hpp",
  },
  hrl = {
    color = "#B83998",
    cterm_color = "163",
    icon = "",
    name = "Hrl",
  },
  hs = {
    color = "#a074c4",
    cterm_color = "140",
    icon = "",
    name = "Hs",
  },
  htm = {
    color = "#e34c26",
    cterm_color = "196",
    icon = "",
    name = "Htm",
  },
  html = {
    color = "#de7558",
    icon = "",
    name = "Html",
  },
  http = {
    color = "#008ec7",
    cterm_color = "31",
    icon = "",
    name = "HTTP",
  },
  huff = {
    color = "#4242c7",
    cterm_color = "56",
    icon = "󰡘",
    name = "Huff",
  },
  hurl = {
    color = "#ff0288",
    cterm_color = "198",
    icon = "",
    name = "Hurl",
  },
  hx = {
    color = "#ea8220",
    cterm_color = "208",
    icon = "",
    name = "Haxe",
  },
  hxx = {
    color = "#a074c4",
    cterm_color = "140",
    icon = "",
    name = "Hxx",
  },
  hyperbola = {
    color = "#c0c0c0",
    cterm_color = "250",
    icon = "",
    name = "HyperbolaGNULinuxLibre",
  },
  ["hypridle.conf"] = {
    color = "#00aaae",
    cterm_color = "37",
    icon = "",
    name = "Hypridle",
  },
  hyprland = {
    color = "#00aaae",
    cterm_color = "37",
    icon = "",
    name = "Hyprland",
  },
  ["hyprland.conf"] = {
    color = "#00aaae",
    cterm_color = "37",
    icon = "",
    name = "Hyprland",
  },
  ["hyprlock.conf"] = {
    color = "#00aaae",
    cterm_color = "37",
    icon = "",
    name = "Hyprlock",
  },
  ["hyprpaper.conf"] = {
    color = "#00aaae",
    cterm_color = "37",
    icon = "",
    name = "Hyprpaper",
  },
  ["i18n.config.js"] = {
    color = "#7986cb",
    cterm_color = "104",
    icon = "󰗊",
    name = "I18nConfig",
  },
  ["i18n.config.ts"] = {
    color = "#7986cb",
    cterm_color = "104",
    icon = "󰗊",
    name = "I18nConfig",
  },
  i3 = {
    color = "#e8ebee",
    cterm_color = "255",
    icon = "",
    name = "i3",
  },
  ["i3blocks.conf"] = {
    color = "#e8ebee",
    cterm_color = "255",
    icon = "",
    name = "i3",
  },
  ["i3status.conf"] = {
    color = "#e8ebee",
    cterm_color = "255",
    icon = "",
    name = "i3",
  },
  ical = {
    color = "#2B2e83",
    cterm_color = "18",
    icon = "",
    name = "Ical",
  },
  icalendar = {
    color = "#2B2e83",
    cterm_color = "18",
    icon = "",
    name = "Icalendar",
  },
  ico = {
    color = "#cbcb41",
    cterm_color = "185",
    icon = "",
    name = "Ico",
  },
  ics = {
    color = "#2B2e83",
    cterm_color = "18",
    icon = "",
    name = "Ics",
  },
  ifb = {
    color = "#2B2e83",
    cterm_color = "18",
    icon = "",
    name = "Ifb",
  },
  ifc = {
    color = "#839463",
    cterm_color = "101",
    icon = "󰻫",
    name = "Ifc",
  },
  ige = {
    color = "#839463",
    cterm_color = "101",
    icon = "󰻫",
    name = "Ige",
  },
  iges = {
    color = "#839463",
    cterm_color = "101",
    icon = "󰻫",
    name = "Iges",
  },
  igs = {
    color = "#839463",
    cterm_color = "101",
    icon = "󰻫",
    name = "Igs",
  },
  illumos = {
    color = "#ff430f",
    cterm_color = "196",
    icon = "",
    name = "Illumos",
  },
  image = {
    color = "#d0bec8",
    cterm_color = "181",
    icon = "",
    name = "Image",
  },
  img = {
    color = "#d0bec8",
    cterm_color = "181",
    icon = "",
    name = "Img",
  },
  import = {
    color = "#ECECEC",
    cterm_color = "255",
    icon = "",
    name = "ImportConfiguration",
  },
  ["index.theme"] = {
    color = "#2DB96F",
    cterm_color = "35",
    icon = "",
    name = "IndexTheme",
  },
  info = {
    color = "#ffffcd",
    cterm_color = "230",
    icon = "",
    name = "Info",
  },
  ini = {
    color = "#6d8086",
    cterm_color = "66",
    icon = "",
    name = "Ini",
  },
  ino = {
    color = "#56b6c2",
    cterm_color = "73",
    icon = "",
    name = "Arduino",
  },
  ["ionic.config.json"] = {
    color = "#4f8ff7",
    cterm_color = "33",
    icon = "",
    name = "Ionic",
  },
  ipynb = {
    color = "#f57d01",
    cterm_color = "208",
    icon = "",
    name = "Notebook",
  },
  iso = {
    color = "#d0bec8",
    cterm_color = "181",
    icon = "",
    name = "Iso",
  },
  ixx = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "Ixx",
  },
  java = {
    icon = "",
    color = "#e46368",
    name = "Java",
  },
  jbuilder = {
    color = "#f7cd6d",
    icon = "",
    name = "Jbuilder",
  },
  jl = {
    color = "#a270ba",
    cterm_color = "133",
    icon = "",
    name = "Jl",
  },
  jpeg = {
    color = "#a074c4",
    cterm_color = "140",
    icon = "",
    name = "Jpeg",
  },
  jpg = {
    color = "#a074c4",
    cterm_color = "140",
    icon = "",
    name = "Jpg",
  },
  js = {
    icon = "󰌞",
    color = "#f7cd6d",
    name = "JavaScript",
  },
  json = {
    color = "#f7cd6d",
    icon = "",
    name = "JSON",
  },
  json5 = {
    color = "#cbcb41",
    cterm_color = "185",
    icon = "",
    name = "Json5",
  },
  jsonc = {
    color = "#cbcb41",
    cterm_color = "185",
    icon = "",
    name = "Jsonc",
  },
  jsx = {
    color = "#20c2e3",
    cterm_color = "45",
    icon = "",
    name = "Jsx",
  },
  justfile = {
    color = "#6d8086",
    cterm_color = "66",
    icon = "",
    name = "Justfile",
  },
  jwm = {
    color = "#0078cd",
    cterm_color = "32",
    icon = "",
    name = "JWM",
  },
  jwmrc = {
    color = "#0078cd",
    cterm_color = "32",
    icon = "",
    name = "JWM",
  },
  jxl = {
    color = "#a074c4",
    cterm_color = "140",
    icon = "",
    name = "JpegXl",
  },
  kalgebrarc = {
    color = "#1c99f3",
    cterm_color = "32",
    icon = "",
    name = "Kalgebrarc",
  },
  kali = {
    color = "#2777ff",
    cterm_color = "69",
    icon = "",
    name = "Kali",
  },
  kbx = {
    color = "#737672",
    cterm_color = "243",
    icon = "󰯄",
    name = "Kbx",
  },
  kdb = {
    color = "#529b34",
    cterm_color = "71",
    icon = "",
    name = "Kdb",
  },
  kdbx = {
    color = "#529b34",
    cterm_color = "71",
    icon = "",
    name = "Kdbx",
  },
  kdeglobals = {
    color = "#1c99f3",
    cterm_color = "32",
    icon = "",
    name = "KDEglobals",
  },
  kdeneon = {
    color = "#20a6a4",
    cterm_color = "37",
    icon = "",
    name = "KDEneon",
  },
  kdenlive = {
    color = "#83b8f2",
    cterm_color = "110",
    icon = "",
    name = "Kdenlive",
  },
  ["kdenlive-layoutsrc"] = {
    color = "#83b8f2",
    cterm_color = "110",
    icon = "",
    name = "KdenliveLayoutsrc",
  },
  kdenliverc = {
    color = "#83b8f2",
    cterm_color = "110",
    icon = "",
    name = "Kdenliverc",
  },
  kdenlivetitle = {
    color = "#83b8f2",
    cterm_color = "110",
    icon = "",
    name = "Kdenlive",
  },
  kicad_dru = {
    color = "#ffffff",
    cterm_color = "231",
    icon = "",
    name = "KiCad",
  },
  kicad_mod = {
    color = "#ffffff",
    cterm_color = "231",
    icon = "",
    name = "KiCad",
  },
  kicad_pcb = {
    color = "#ffffff",
    cterm_color = "231",
    icon = "",
    name = "KiCad",
  },
  kicad_prl = {
    color = "#ffffff",
    cterm_color = "231",
    icon = "",
    name = "KiCad",
  },
  kicad_pro = {
    color = "#ffffff",
    cterm_color = "231",
    icon = "",
    name = "KiCad",
  },
  kicad_sch = {
    color = "#ffffff",
    cterm_color = "231",
    icon = "",
    name = "KiCad",
  },
  kicad_sym = {
    color = "#ffffff",
    cterm_color = "231",
    icon = "",
    name = "KiCad",
  },
  kicad_wks = {
    color = "#ffffff",
    cterm_color = "231",
    icon = "",
    name = "KiCad",
  },
  ko = {
    color = "#dcddd6",
    cterm_color = "253",
    icon = "",
    name = "LinuxKernelObject",
  },
  kpp = {
    color = "#f245fb",
    cterm_color = "201",
    icon = "",
    name = "Krita",
  },
  kra = {
    color = "#f245fb",
    cterm_color = "201",
    icon = "",
    name = "Krita",
  },
  kritadisplayrc = {
    color = "#f245fb",
    cterm_color = "201",
    icon = "",
    name = "Kritadisplayrc",
  },
  kritarc = {
    color = "#f245fb",
    cterm_color = "201",
    icon = "",
    name = "Kritarc",
  },
  krz = {
    color = "#f245fb",
    cterm_color = "201",
    icon = "",
    name = "Krita",
  },
  ksh = {
    color = "#4d5a5e",
    cterm_color = "240",
    icon = "",
    name = "Ksh",
  },
  kt = {
    color = "#7F52FF",
    cterm_color = "99",
    icon = "",
    name = "Kotlin",
  },
  kts = {
    color = "#7F52FF",
    cterm_color = "99",
    icon = "",
    name = "KotlinScript",
  },
  kubuntu = {
    color = "#007ac2",
    cterm_color = "32",
    icon = "",
    name = "Kubuntu",
  },
  lck = {
    color = "#bbbbbb",
    cterm_color = "250",
    icon = "",
    name = "Lock",
  },
  leap = {
    color = "#FBC75D",
    cterm_color = "221",
    icon = "",
    name = "Leap",
  },
  leex = {
    color = "#a074c4",
    cterm_color = "140",
    icon = "",
    name = "Leex",
  },
  less = {
    color = "#563d7c",
    cterm_color = "54",
    icon = "",
    name = "Less",
  },
  lff = {
    color = "#ECECEC",
    cterm_color = "255",
    icon = "",
    name = "LibrecadFontFile",
  },
  lhs = {
    color = "#a074c4",
    cterm_color = "140",
    icon = "",
    name = "Lhs",
  },
  lib = {
    color = "#4d2c0b",
    cterm_color = "52",
    icon = "",
    name = "Lib",
  },
  license = {
    color = "#d0bf41",
    cterm_color = "185",
    icon = "",
    name = "License",
  },
  ["license.md"] = {
    color = "#d0bf41",
    cterm_color = "185",
    icon = "",
    name = "License",
  },
  linux = {
    color = "#fdfdfb",
    cterm_color = "231",
    icon = "",
    name = "Linux",
  },
  liquid = {
    color = "#95BF47",
    cterm_color = "106",
    icon = "",
    name = "Liquid",
  },
  lock = {
    color = "#bbbbbb",
    cterm_color = "250",
    icon = "",
    name = "Lock",
  },
  locos = {
    color = "#fab402",
    cterm_color = "214",
    icon = "",
    name = "LocOS",
  },
  log = {
    color = "#dddddd",
    cterm_color = "253",
    icon = "󰌱",
    name = "Log",
  },
  lrc = {
    color = "#ffb713",
    cterm_color = "214",
    icon = "󰨖",
    name = "Lrc",
  },
  lua = {
    color = "#5166f0",
    icon = "",
    name = "Lua",
  },
  luac = {
    icon = "",
    color = "#5166f0",
    name = "Lua",
  },
  luau = {
    color = "#00a2ff",
    cterm_color = "75",
    icon = "",
    name = "Luau",
  },
  lxde = {
    color = "#a4a4a4",
    cterm_color = "248",
    icon = "",
    name = "LXDE",
  },
  ["lxde-rc.xml"] = {
    color = "#909090",
    cterm_color = "246",
    icon = "",
    name = "LXDEConfigFile",
  },
  lxle = {
    color = "#474747",
    cterm_color = "238",
    icon = "",
    name = "LXLE",
  },
  lxqt = {
    color = "#0191d2",
    cterm_color = "32",
    icon = "",
    name = "LXQt",
  },
  ["lxqt.conf"] = {
    color = "#0192d3",
    cterm_color = "32",
    icon = "",
    name = "LXQtConfigFile",
  },
  m = {
    color = "#599eff",
    cterm_color = "111",
    icon = "",
    name = "ObjectiveC",
  },
  m3u = {
    color = "#ed95ae",
    cterm_color = "211",
    icon = "󰲹",
    name = "M3u",
  },
  m3u8 = {
    color = "#ed95ae",
    cterm_color = "211",
    icon = "󰲹",
    name = "M3u8",
  },
  m4a = {
    color = "#00afff",
    cterm_color = "39",
    icon = "",
    name = "MPEG4",
  },
  m4v = {
    color = "#FD971F",
    cterm_color = "208",
    icon = "",
    name = "M4V",
  },
  mageia = {
    color = "#2397d4",
    cterm_color = "67",
    icon = "",
    name = "Mageia",
  },
  magnet = {
    color = "#a51b16",
    cterm_color = "124",
    icon = "",
    name = "Magnet",
  },
  makefile = {
    color = "#6d8086",
    cterm_color = "66",
    icon = "",
    name = "Makefile",
  },
  manjaro = {
    color = "#33b959",
    cterm_color = "35",
    icon = "",
    name = "Manjaro",
  },
  markdown = {
    color = "#dddddd",
    cterm_color = "253",
    icon = "",
    name = "Markdown",
  },
  mate = {
    color = "#9bda5c",
    cterm_color = "113",
    icon = "",
    name = "MATE",
  },
  material = {
    color = "#B83998",
    cterm_color = "163",
    icon = "",
    name = "Material",
  },
  md = {
    color = "#dddddd",
    cterm_color = "253",
    icon = "",
    name = "Md",
  },
  md5 = {
    color = "#8c86af",
    cterm_color = "103",
    icon = "󰕥",
    name = "Md5",
  },
  mdx = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "Mdx",
  },
  mint = {
    color = "#87c095",
    cterm_color = "108",
    icon = "󰌪",
    name = "Mint",
  },
  ["mix.lock"] = {
    color = "#a074c4",
    cterm_color = "140",
    icon = "",
    name = "MixLock",
  },
  mjs = {
    color = "#f1e05a",
    cterm_color = "185",
    icon = "",
    name = "Mjs",
  },
  mk = {
    color = "#6d8086",
    cterm_color = "66",
    icon = "",
    name = "Makefile",
  },
  mkv = {
    color = "#FD971F",
    cterm_color = "208",
    icon = "",
    name = "Mkv",
  },
  ml = {
    color = "#e37933",
    cterm_color = "166",
    icon = "",
    name = "Ml",
  },
  mli = {
    color = "#e37933",
    cterm_color = "166",
    icon = "",
    name = "Mli",
  },
  mm = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "ObjectiveCPlusPlus",
  },
  mo = {
    color = "#9772FB",
    cterm_color = "135",
    icon = "",
    name = "Motoko",
  },
  mobi = {
    color = "#eab16d",
    cterm_color = "215",
    icon = "",
    name = "Mobi",
  },
  mojo = {
    color = "#ff4c1f",
    cterm_color = "196",
    icon = "",
    name = "Mojo",
  },
  mov = {
    color = "#FD971F",
    cterm_color = "208",
    icon = "",
    name = "MOV",
  },
  mp3 = {
    color = "#00afff",
    cterm_color = "39",
    icon = "",
    name = "MPEGAudioLayerIII",
  },
  mp4 = {
    color = "#FD971F",
    cterm_color = "208",
    icon = "",
    name = "Mp4",
  },
  mpp = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "Mpp",
  },
  ["mpv.conf"] = {
    color = "#3b1342",
    cterm_color = "53",
    icon = "",
    name = "Mpv",
  },
  msf = {
    color = "#137be1",
    cterm_color = "33",
    icon = "",
    name = "Thunderbird",
  },
  mts = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "Mts",
  },
  mustache = {
    color = "#e37933",
    cterm_color = "166",
    icon = "",
    name = "Mustache",
  },
  mxlinux = {
    color = "#ffffff",
    cterm_color = "231",
    icon = "",
    name = "MXLinux",
  },
  nfo = {
    color = "#ffffcd",
    cterm_color = "230",
    icon = "",
    name = "Nfo",
  },
  nim = {
    color = "#f3d400",
    cterm_color = "220",
    icon = "",
    name = "Nim",
  },
  nix = {
    color = "#7ebae4",
    cterm_color = "110",
    icon = "",
    name = "Nix",
  },
  nixos = {
    color = "#7ab1db",
    cterm_color = "110",
    icon = "",
    name = "NixOS",
  },
  nobara = {
    color = "#ffffff",
    cterm_color = "231",
    icon = "",
    name = "NobaraLinux",
  },
  node_modules = {
    color = "#E8274B",
    cterm_color = "197",
    icon = "",
    name = "NodeModules",
  },
  norg = {
    color = "#4878be",
    cterm_color = "32",
    icon = "",
    name = "Norg",
  },
  nswag = {
    color = "#85ea2d",
    cterm_color = "112",
    icon = "",
    name = "Nswag",
  },
  nu = {
    color = "#3aa675",
    cterm_color = "36",
    icon = "",
    name = "Nushell",
  },
  ["nuxt.config.cjs"] = {
    color = "#00c58e",
    cterm_color = "42",
    icon = "󱄆",
    name = "NuxtConfig",
  },
  ["nuxt.config.js"] = {
    color = "#00c58e",
    cterm_color = "42",
    icon = "󱄆",
    name = "NuxtConfig",
  },
  ["nuxt.config.mjs"] = {
    color = "#00c58e",
    cterm_color = "42",
    icon = "󱄆",
    name = "NuxtConfig",
  },
  ["nuxt.config.ts"] = {
    color = "#00c58e",
    cterm_color = "42",
    icon = "󱄆",
    name = "NuxtConfig",
  },
  o = {
    color = "#9F0500",
    cterm_color = "124",
    icon = "",
    name = "ObjectFile",
  },
  obj = {
    color = "#888888",
    cterm_color = "102",
    icon = "󰆧",
    name = "3DObjectFile",
  },
  odf = {
    color = "#FF5A96",
    cterm_color = "204",
    icon = "",
    name = "LibreOfficeFormula",
  },
  odg = {
    color = "#FFFB57",
    cterm_color = "227",
    icon = "",
    name = "LibreOfficeGraphics",
  },
  odin = {
    color = "#3882D2",
    cterm_color = "32",
    icon = "󰟢",
    name = "Odin",
  },
  odp = {
    color = "#FE9C45",
    cterm_color = "215",
    icon = "",
    name = "LibreOfficeImpress",
  },
  ods = {
    color = "#78FC4E",
    cterm_color = "119",
    icon = "",
    name = "LibreOfficeCalc",
  },
  odt = {
    color = "#2DCBFD",
    cterm_color = "81",
    icon = "",
    name = "LibreOfficeWriter",
  },
  ogg = {
    color = "#0075aa",
    cterm_color = "24",
    icon = "",
    name = "OggVorbis",
  },
  openbsd = {
    color = "#f2ca30",
    cterm_color = "220",
    icon = "",
    name = "OpenBSD",
  },
  opensuse = {
    color = "#6fb424",
    cterm_color = "70",
    icon = "",
    name = "openSUSE",
  },
  opus = {
    color = "#0075aa",
    cterm_color = "24",
    icon = "",
    name = "OpusAudioFile",
  },
  org = {
    color = "#77AA99",
    cterm_color = "73",
    icon = "",
    name = "OrgMode",
  },
  otf = {
    color = "#ECECEC",
    cterm_color = "255",
    icon = "",
    name = "OpenTypeFont",
  },
  out = {
    color = "#9F0500",
    cterm_color = "124",
    icon = "",
    name = "Out",
  },
  ["package-lock.json"] = {
    color = "#7a0d21",
    cterm_color = "52",
    icon = "",
    name = "PackageLockJson",
  },
  ["package.json"] = {
    color = "#e8274b",
    cterm_color = "197",
    icon = "",
    name = "PackageJson",
  },
  parabola = {
    color = "#797dac",
    cterm_color = "103",
    icon = "",
    name = "ParabolaGNULinuxLibre",
  },
  parrot = {
    color = "#54deff",
    cterm_color = "45",
    icon = "",
    name = "Parrot",
  },
  part = {
    color = "#44cda8",
    cterm_color = "43",
    icon = "",
    name = "Part",
  },
  patch = {
    color = "#41535b",
    cterm_color = "239",
    icon = "",
    name = "Patch",
  },
  pck = {
    color = "#6d8086",
    cterm_color = "66",
    icon = "",
    name = "PackedResource",
  },
  pcm = {
    color = "#0075aa",
    cterm_color = "24",
    icon = "",
    name = "PulseCodeModulation",
  },
  pdf = {
    color = "#b30b00",
    cterm_color = "124",
    icon = "",
    name = "Pdf",
  },
  php = {
    color = "#a074c4",
    cterm_color = "140",
    icon = "",
    name = "Php",
  },
  pkgbuild = {
    color = "#0f94d2",
    cterm_color = "67",
    icon = "",
    name = "PKGBUILD",
  },
  pl = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "Pl",
  },
  plasma = {
    color = "#1b89f4",
    cterm_color = "33",
    icon = "",
    name = "KDEPlasma",
  },
  ["platformio.ini"] = {
    color = "#f6822b",
    cterm_color = "208",
    icon = "",
    name = "Platformio",
  },
  pls = {
    color = "#ed95ae",
    cterm_color = "211",
    icon = "󰲹",
    name = "Pls",
  },
  ply = {
    color = "#888888",
    cterm_color = "102",
    icon = "󰆧",
    name = "3DObjectFile",
  },
  pm = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "Pm",
  },
  png = {
    color = "#a074c4",
    cterm_color = "140",
    icon = "",
    name = "Png",
  },
  po = {
    color = "#2596be",
    cterm_color = "31",
    icon = "",
    name = "Localization",
  },
  ["pom.xml"] = {
    color = "#7a0d21",
    cterm_color = "52",
    icon = "",
    name = "Maven",
  },
  pop_os = {
    color = "#48b9c7",
    cterm_color = "73",
    icon = "",
    name = "Pop_OS",
  },
  postmarketos = {
    color = "#009900",
    cterm_color = "28",
    icon = "",
    name = "postmarketOS",
  },
  pot = {
    color = "#2596be",
    cterm_color = "31",
    icon = "",
    name = "Localization",
  },
  pp = {
    color = "#FFA61A",
    cterm_color = "214",
    icon = "",
    name = "Pp",
  },
  ppt = {
    color = "#cb4a32",
    cterm_color = "160",
    icon = "󰈧",
    name = "Ppt",
  },
  pptx = {
    color = "#cb4a32",
    cterm_color = "160",
    icon = "󰈧",
    name = "Pptx",
  },
  ["prettier.config.cjs"] = {
    color = "#4285F4",
    cterm_color = "33",
    icon = "",
    name = "PrettierConfig",
  },
  ["prettier.config.js"] = {
    color = "#4285F4",
    cterm_color = "33",
    icon = "",
    name = "PrettierConfig",
  },
  ["prettier.config.mjs"] = {
    color = "#4285F4",
    cterm_color = "33",
    icon = "",
    name = "PrettierConfig",
  },
  ["prettier.config.ts"] = {
    color = "#4285F4",
    cterm_color = "33",
    icon = "",
    name = "PrettierConfig",
  },
  prisma = {
    color = "#5a67d8",
    cterm_color = "62",
    icon = "",
    name = "Prisma",
  },
  pro = {
    color = "#e4b854",
    cterm_color = "179",
    icon = "",
    name = "Prolog",
  },
  procfile = {
    color = "#a074c4",
    cterm_color = "140",
    icon = "",
    name = "Procfile",
  },
  ["prusaslicer.ini"] = {
    color = "#ec6b23",
    cterm_color = "202",
    icon = "",
    name = "PrusaSlicer",
  },
  ["prusaslicergcodeviewer.ini"] = {
    color = "#ec6b23",
    cterm_color = "202",
    icon = "",
    name = "PrusaSlicer",
  },
  ps1 = {
    color = "#4273ca",
    cterm_color = "68",
    icon = "󰨊",
    name = "PsScriptfile",
  },
  psb = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "Psb",
  },
  psd = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "Psd",
  },
  psd1 = {
    color = "#6975c4",
    cterm_color = "68",
    icon = "󰨊",
    name = "PsManifestfile",
  },
  psm1 = {
    color = "#6975c4",
    cterm_color = "68",
    icon = "󰨊",
    name = "PsScriptModulefile",
  },
  pub = {
    color = "#e3c58e",
    cterm_color = "222",
    icon = "󰷖",
    name = "Pub",
  },
  puppylinux = {
    color = "#a2aeb9",
    cterm_color = "145",
    icon = "",
    name = "PuppyLinux",
  },
  pxd = {
    color = "#5aa7e4",
    cterm_color = "39",
    icon = "",
    name = "Pxd",
  },
  pxi = {
    color = "#5aa7e4",
    cterm_color = "39",
    icon = "",
    name = "Pxi",
  },
  py = {
    color = "#ffbc03",
    cterm_color = "214",
    icon = "",
    name = "Py",
  },
  ["py.typed"] = {
    color = "#ffbc03",
    cterm_color = "214",
    icon = "",
    name = "Py.typed",
  },
  pyc = {
    color = "#ffe291",
    cterm_color = "222",
    icon = "",
    name = "Pyc",
  },
  pyd = {
    color = "#ffe291",
    cterm_color = "222",
    icon = "",
    name = "Pyd",
  },
  pyi = {
    color = "#ffbc03",
    cterm_color = "214",
    icon = "",
    name = "Pyi",
  },
  pyo = {
    color = "#ffe291",
    cterm_color = "222",
    icon = "",
    name = "Pyo",
  },
  pyw = {
    color = "#5aa7e4",
    cterm_color = "39",
    icon = "",
    name = "Pyw",
  },
  pyx = {
    color = "#5aa7e4",
    cterm_color = "39",
    icon = "",
    name = "Pyx",
  },
  qm = {
    color = "#2596be",
    cterm_color = "31",
    icon = "",
    name = "Localization",
  },
  qml = {
    color = "#40cd52",
    cterm_color = "77",
    icon = "",
    name = "Qt",
  },
  qrc = {
    color = "#40cd52",
    cterm_color = "77",
    icon = "",
    name = "Qt",
  },
  qss = {
    color = "#40cd52",
    cterm_color = "77",
    icon = "",
    name = "Qt",
  },
  qtile = {
    color = "#ffffff",
    cterm_color = "231",
    icon = "",
    name = "Qtile",
  },
  ["qtproject.conf"] = {
    color = "#40cd52",
    cterm_color = "77",
    icon = "",
    name = "Qt",
  },
  qubesos = {
    color = "#3774d8",
    cterm_color = "33",
    icon = "",
    name = "QubesOS",
  },
  query = {
    color = "#90a850",
    cterm_color = "107",
    icon = "",
    name = "Query",
  },
  r = {
    color = "#2266ba",
    cterm_color = "25",
    icon = "󰟔",
    name = "R",
  },
  rake = {
    color = "#ef757c",
    icon = "",
    name = "Rake",
  },
  rakefile = {
    color = "#ef757c",
    icon = "",
    name = "RakeFile",
  },
  rar = {
    color = "#eca517",
    cterm_color = "214",
    icon = "",
    name = "Rar",
  },
  raspberry_pi = {
    color = "#be1848",
    cterm_color = "161",
    icon = "",
    name = "RaspberryPiOS",
  },
  razor = {
    color = "#512bd4",
    cterm_color = "56",
    icon = "󱦘",
    name = "RazorPage",
  },
  rb = {
    color = "#ef757c",
    icon = "",
    name = "Rb",
  },
  readme = {
    color = "#ededed",
    cterm_color = "255",
    icon = "󰂺",
    name = "Readme",
  },
  ["readme.md"] = {
    color = "#ededed",
    cterm_color = "255",
    icon = "󰂺",
    name = "Readme",
  },
  redhat = {
    color = "#EE0000",
    cterm_color = "196",
    icon = "󱄛",
    name = "Redhat",
  },
  res = {
    color = "#cc3e44",
    cterm_color = "167",
    icon = "",
    name = "ReScript",
  },
  resi = {
    color = "#f55385",
    cterm_color = "204",
    icon = "",
    name = "ReScriptInterface",
  },
  river = {
    color = "#000000",
    cterm_color = "16",
    icon = "",
    name = "river",
  },
  rlib = {
    color = "#dea584",
    cterm_color = "216",
    icon = "",
    name = "Rlib",
  },
  rmd = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "Rmd",
  },
  ["robots.txt"] = {
    color = "#5d7096",
    cterm_color = "60",
    icon = "󰚩",
    name = "RobotsTxt",
  },
  rocky = {
    color = "#0fb37d",
    cterm_color = "36",
    icon = "",
    name = "RockyLinux",
  },
  rproj = {
    color = "#358a5b",
    cterm_color = "29",
    icon = "󰗆",
    name = "Rproj",
  },
  rs = {
    color = "#dea584",
    cterm_color = "216",
    icon = "",
    name = "Rs",
  },
  rss = {
    color = "#FB9D3B",
    cterm_color = "215",
    icon = "",
    name = "Rss",
  },
  s = {
    color = "#0071C5",
    cterm_color = "25",
    icon = "",
    name = "ASM",
  },
  sabayon = {
    color = "#c6c6c6",
    cterm_color = "251",
    icon = "",
    name = "Sabayon",
  },
  sass = {
    color = "#f55385",
    cterm_color = "204",
    icon = "",
    name = "Sass",
  },
  sbt = {
    color = "#cc3e44",
    cterm_color = "167",
    icon = "",
    name = "sbt",
  },
  sc = {
    color = "#cc3e44",
    cterm_color = "167",
    icon = "",
    name = "ScalaScript",
  },
  scad = {
    color = "#f9d72c",
    cterm_color = "220",
    icon = "",
    name = "OpenSCAD",
  },
  scala = {
    color = "#cc3e44",
    cterm_color = "167",
    icon = "",
    name = "Scala",
  },
  scm = {
    color = "#eeeeee",
    cterm_color = "255",
    icon = "󰘧",
    name = "Scheme",
  },
  scss = {
    color = "#f55385",
    cterm_color = "204",
    icon = "",
    name = "Scss",
  },
  security = {
    color = "#BEC4C9",
    cterm_color = "251",
    icon = "󰒃",
    name = "Security",
  },
  ["security.md"] = {
    color = "#BEC4C9",
    cterm_color = "251",
    icon = "󰒃",
    name = "Security",
  },
  ["settings.gradle"] = {
    color = "#005f87",
    cterm_color = "24",
    icon = "",
    name = "GradleSettings",
  },
  sh = {
    color = "#4d5a5e",
    cterm_color = "240",
    icon = "",
    name = "Sh",
  },
  sha1 = {
    color = "#8c86af",
    cterm_color = "103",
    icon = "󰕥",
    name = "Sha1",
  },
  sha224 = {
    color = "#8c86af",
    cterm_color = "103",
    icon = "󰕥",
    name = "Sha224",
  },
  sha256 = {
    color = "#8c86af",
    cterm_color = "103",
    icon = "󰕥",
    name = "Sha256",
  },
  sha384 = {
    color = "#8c86af",
    cterm_color = "103",
    icon = "󰕥",
    name = "Sha384",
  },
  sha512 = {
    color = "#8c86af",
    cterm_color = "103",
    icon = "󰕥",
    name = "Sha512",
  },
  sig = {
    color = "#e37933",
    cterm_color = "166",
    icon = "󰘧",
    name = "Sig",
  },
  signature = {
    color = "#e37933",
    cterm_color = "166",
    icon = "󰘧",
    name = "Signature",
  },
  skp = {
    color = "#839463",
    cterm_color = "101",
    icon = "󰻫",
    name = "SketchUp",
  },
  slackware = {
    color = "#475fa9",
    cterm_color = "61",
    icon = "",
    name = "Slackware",
  },
  sldasm = {
    color = "#839463",
    cterm_color = "101",
    icon = "󰻫",
    name = "SolidWorksAsm",
  },
  sldprt = {
    color = "#839463",
    cterm_color = "101",
    icon = "󰻫",
    name = "SolidWorksPrt",
  },
  slim = {
    color = "#e34c26",
    cterm_color = "196",
    icon = "",
    name = "Slim",
  },
  sln = {
    color = "#854CC7",
    cterm_color = "98",
    icon = "",
    name = "Sln",
  },
  slvs = {
    color = "#839463",
    cterm_color = "101",
    icon = "󰻫",
    name = "SolveSpace",
  },
  sml = {
    color = "#e37933",
    cterm_color = "166",
    icon = "󰘧",
    name = "Sml",
  },
  so = {
    color = "#dcddd6",
    cterm_color = "253",
    icon = "",
    name = "SharedObject",
  },
  sol = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "Solidity",
  },
  solus = {
    color = "#4b5163",
    cterm_color = "239",
    icon = "",
    name = "Solus",
  },
  ["spec.js"] = {
    color = "#cbcb41",
    cterm_color = "185",
    icon = "",
    name = "SpecJs",
  },
  ["spec.jsx"] = {
    color = "#20c2e3",
    cterm_color = "45",
    icon = "",
    name = "JavaScriptReactSpec",
  },
  ["spec.ts"] = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "SpecTs",
  },
  ["spec.tsx"] = {
    color = "#1354bf",
    cterm_color = "26",
    icon = "",
    name = "TypeScriptReactSpec",
  },
  sql = {
    color = "#dad8d8",
    cterm_color = "188",
    icon = "",
    name = "Sql",
  },
  sqlite = {
    color = "#dad8d8",
    cterm_color = "188",
    icon = "",
    name = "Sql",
  },
  sqlite3 = {
    color = "#dad8d8",
    cterm_color = "188",
    icon = "",
    name = "Sql",
  },
  srt = {
    color = "#ffb713",
    cterm_color = "214",
    icon = "󰨖",
    name = "Srt",
  },
  ssa = {
    color = "#ffb713",
    cterm_color = "214",
    icon = "󰨖",
    name = "Ssa",
  },
  ste = {
    color = "#839463",
    cterm_color = "101",
    icon = "󰻫",
    name = "Ste",
  },
  step = {
    color = "#839463",
    cterm_color = "101",
    icon = "󰻫",
    name = "Step",
  },
  stl = {
    color = "#888888",
    cterm_color = "102",
    icon = "󰆧",
    name = "3DObjectFile",
  },
  stp = {
    color = "#839463",
    cterm_color = "101",
    icon = "󰻫",
    name = "Stp",
  },
  strings = {
    color = "#2596be",
    cterm_color = "31",
    icon = "",
    name = "Localization",
  },
  styl = {
    color = "#8dc149",
    cterm_color = "113",
    icon = "",
    name = "Styl",
  },
  sub = {
    color = "#ffb713",
    cterm_color = "214",
    icon = "󰨖",
    name = "Sub",
  },
  sublime = {
    color = "#e37933",
    cterm_color = "166",
    icon = "",
    name = "Sublime",
  },
  suo = {
    color = "#854CC7",
    cterm_color = "98",
    icon = "",
    name = "Suo",
  },
  sv = {
    color = "#019833",
    cterm_color = "28",
    icon = "󰍛",
    name = "SystemVerilog",
  },
  svelte = {
    color = "#ff3e00",
    cterm_color = "196",
    icon = "",
    name = "Svelte",
  },
  ["svelte.config.js"] = {
    color = "#ff3e00",
    cterm_color = "196",
    icon = "",
    name = "SvelteConfig",
  },
  svg = {
    color = "#FFB13B",
    cterm_color = "214",
    icon = "󰜡",
    name = "Svg",
  },
  svh = {
    color = "#019833",
    cterm_color = "28",
    icon = "󰍛",
    name = "SystemVerilog",
  },
  sway = {
    color = "#68751c",
    cterm_color = "64",
    icon = "",
    name = "Sway",
  },
  swift = {
    color = "#e37933",
    cterm_color = "166",
    icon = "",
    name = "Swift",
  },
  sxhkdrc = {
    color = "#2f2f2f",
    cterm_color = "236",
    icon = "",
    name = "BSPWM",
  },
  ["sym-lib-table"] = {
    color = "#ffffff",
    cterm_color = "231",
    icon = "",
    name = "KiCadSymbolTable",
  },
  t = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "Tor",
  },
  tails = {
    color = "#56347c",
    cterm_color = "54",
    icon = "",
    name = "Tails",
  },
  ["tailwind.config.js"] = {
    color = "#20c2e3",
    cterm_color = "45",
    icon = "󱏿",
    name = "TailwindConfig",
  },
  ["tailwind.config.mjs"] = {
    color = "#20c2e3",
    cterm_color = "45",
    icon = "󱏿",
    name = "TailwindConfig",
  },
  ["tailwind.config.ts"] = {
    color = "#20c2e3",
    cterm_color = "45",
    icon = "󱏿",
    name = "TailwindConfig",
  },
  tbc = {
    color = "#1e5cb3",
    cterm_color = "25",
    icon = "󰛓",
    name = "Tcl",
  },
  tcl = {
    color = "#1e5cb3",
    cterm_color = "25",
    icon = "󰛓",
    name = "Tcl",
  },
  templ = {
    color = "#dbbd30",
    cterm_color = "178",
    icon = "",
    name = "Templ",
  },
  terminal = {
    color = "#31B53E",
    cterm_color = "34",
    icon = "",
    name = "Terminal",
  },
  ["test.js"] = {
    color = "#cbcb41",
    cterm_color = "185",
    icon = "",
    name = "TestJs",
  },
  ["test.jsx"] = {
    color = "#20c2e3",
    cterm_color = "45",
    icon = "",
    name = "JavaScriptReactTest",
  },
  ["test.ts"] = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "TestTs",
  },
  ["test.tsx"] = {
    color = "#1354bf",
    cterm_color = "26",
    icon = "",
    name = "TypeScriptReactTest",
  },
  tex = {
    color = "#3D6117",
    cterm_color = "22",
    icon = "",
    name = "Tex",
  },
  tf = {
    color = "#5F43E9",
    cterm_color = "93",
    icon = "",
    name = "Terraform",
  },
  tfvars = {
    color = "#5F43E9",
    cterm_color = "93",
    icon = "",
    name = "TFVars",
  },
  tgz = {
    color = "#eca517",
    cterm_color = "214",
    icon = "",
    name = "Tgz",
  },
  tmux = {
    color = "#14ba19",
    cterm_color = "34",
    icon = "",
    name = "Tmux",
  },
  ["tmux.conf"] = {
    color = "#14ba19",
    cterm_color = "34",
    icon = "",
    name = "Tmux",
  },
  ["tmux.conf.local"] = {
    color = "#14ba19",
    cterm_color = "34",
    icon = "",
    name = "Tmux",
  },
  toml = {
    color = "#9c4221",
    cterm_color = "124",
    icon = "",
    name = "Toml",
  },
  torrent = {
    color = "#44cda8",
    cterm_color = "43",
    icon = "",
    name = "Torrent",
  },
  tres = {
    color = "#6d8086",
    cterm_color = "66",
    icon = "",
    name = "GodotTextResource",
  },
  trisquel = {
    color = "#0f58b6",
    cterm_color = "25",
    icon = "",
    name = "TrisquelGNULinux",
  },
  ts = {
    color = "#87b2e2",
    icon = "󰛦",
    name = "TypeScript",
  },
  tscn = {
    color = "#6d8086",
    cterm_color = "66",
    icon = "",
    name = "GodotTextScene",
  },
  tsconfig = {
    color = "#FF8700",
    cterm_color = "208",
    icon = "",
    name = "TypoScriptConfig",
  },
  ["tsconfig.json"] = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "TSConfig",
  },
  tsx = {
    color = "#1354bf",
    cterm_color = "26",
    icon = "",
    name = "Tsx",
  },
  ttf = {
    color = "#ECECEC",
    cterm_color = "255",
    icon = "",
    name = "TrueTypeFont",
  },
  tumbleweed = {
    color = "#35B9AB",
    cterm_color = "37",
    icon = "",
    name = "Tumbleweed",
  },
  twig = {
    color = "#8dc149",
    cterm_color = "113",
    icon = "",
    name = "Twig",
  },
  txt = {
    color = "#89e051",
    cterm_color = "113",
    icon = "󰈙",
    name = "Txt",
  },
  txz = {
    color = "#eca517",
    cterm_color = "214",
    icon = "",
    name = "Txz",
  },
  typ = {
    color = "#0dbcc0",
    cterm_color = "37",
    icon = "",
    name = "Typst",
  },
  typoscript = {
    color = "#FF8700",
    cterm_color = "208",
    icon = "",
    name = "TypoScript",
  },
  ubuntu = {
    color = "#dd4814",
    cterm_color = "196",
    icon = "",
    name = "Ubuntu",
  },
  ui = {
    color = "#015BF0",
    cterm_color = "27",
    icon = "",
    name = "UI",
  },
  unlicense = {
    color = "#d0bf41",
    cterm_color = "185",
    icon = "",
    name = "License",
  },
  v = {
    color = "#019833",
    cterm_color = "28",
    icon = "󰍛",
    name = "Verilog",
  },
  vagrantfile = {
    color = "#1563FF",
    cterm_color = "27",
    icon = "",
    name = "Vagrantfile",
  },
  vala = {
    color = "#7b3db9",
    cterm_color = "91",
    icon = "",
    name = "Vala",
  },
  vanillaos = {
    color = "#fabd4d",
    cterm_color = "214",
    icon = "",
    name = "VanillaOS",
  },
  ["vercel.json"] = {
    color = "#ffffff",
    cterm_color = "231",
    icon = "",
    name = "Vercel",
  },
  vh = {
    color = "#019833",
    cterm_color = "28",
    icon = "󰍛",
    name = "Verilog",
  },
  vhd = {
    color = "#019833",
    cterm_color = "28",
    icon = "󰍛",
    name = "VHDL",
  },
  vhdl = {
    color = "#019833",
    cterm_color = "28",
    icon = "󰍛",
    name = "VHDL",
  },
  vi = {
    color = "#fec60a",
    cterm_color = "220",
    icon = "",
    name = "LabView",
  },
  vim = {
    color = "#019833",
    cterm_color = "28",
    icon = "",
    name = "Vim",
  },
  vlcrc = {
    color = "#ee7a00",
    cterm_color = "208",
    icon = "󰕼",
    name = "VLC",
  },
  void = {
    color = "#295340",
    cterm_color = "23",
    icon = "",
    name = "Void",
  },
  vsh = {
    color = "#5d87bf",
    cterm_color = "67",
    icon = "",
    name = "Vlang",
  },
  vsix = {
    color = "#854CC7",
    cterm_color = "98",
    icon = "",
    name = "Vsix",
  },
  vue = {
    color = "#8dc149",
    cterm_color = "113",
    icon = "",
    name = "Vue",
  },
  wasm = {
    color = "#5c4cdb",
    cterm_color = "62",
    icon = "",
    name = "Wasm",
  },
  wav = {
    color = "#00afff",
    cterm_color = "39",
    icon = "",
    name = "WaveformAudioFile",
  },
  webm = {
    color = "#FD971F",
    cterm_color = "208",
    icon = "",
    name = "Webm",
  },
  webmanifest = {
    color = "#f1e05a",
    cterm_color = "185",
    icon = "",
    name = "Webmanifest",
  },
  webp = {
    color = "#a074c4",
    cterm_color = "140",
    icon = "",
    name = "Webp",
  },
  webpack = {
    color = "#519aba",
    cterm_color = "74",
    icon = "󰜫",
    name = "Webpack",
  },
  ["weston.ini"] = {
    color = "#ffbb01",
    cterm_color = "214",
    icon = "",
    name = "Weston",
  },
  windows = {
    color = "#00A4EF",
    cterm_color = "39",
    icon = "",
    name = "Windows",
  },
  wma = {
    color = "#00afff",
    cterm_color = "39",
    icon = "",
    name = "WindowsMediaAudio",
  },
  woff = {
    color = "#ECECEC",
    cterm_color = "255",
    icon = "",
    name = "WebOpenFontFormat",
  },
  woff2 = {
    color = "#ECECEC",
    cterm_color = "255",
    icon = "",
    name = "WebOpenFontFormat",
  },
  workspace = {
    color = "#89e051",
    cterm_color = "113",
    icon = "",
    name = "BazelWorkspace",
  },
  wrl = {
    color = "#888888",
    cterm_color = "102",
    icon = "󰆧",
    name = "VRML",
  },
  wrz = {
    color = "#888888",
    cterm_color = "102",
    icon = "󰆧",
    name = "VRML",
  },
  wv = {
    color = "#00afff",
    cterm_color = "39",
    icon = "",
    name = "WavPack",
  },
  wvc = {
    color = "#00afff",
    cterm_color = "39",
    icon = "",
    name = "WavPackCorrection",
  },
  x = {
    color = "#599eff",
    cterm_color = "111",
    icon = "",
    name = "Logos",
  },
  xaml = {
    color = "#512bd4",
    cterm_color = "56",
    icon = "󰙳",
    name = "Xaml",
  },
  xcf = {
    color = "#635b46",
    cterm_color = "240",
    icon = "",
    name = "GIMP",
  },
  xcplayground = {
    color = "#e37933",
    cterm_color = "166",
    icon = "",
    name = "XcPlayground",
  },
  xcstrings = {
    color = "#2596be",
    cterm_color = "31",
    icon = "",
    name = "XcLocalization",
  },
  xerolinux = {
    color = "#888fe2",
    cterm_color = "104",
    icon = "",
    name = "XeroLinux",
  },
  xfce = {
    color = "#00aadf",
    cterm_color = "74",
    icon = "",
    name = "Xfce",
  },
  xls = {
    color = "#207245",
    cterm_color = "29",
    icon = "󰈛",
    name = "Xls",
  },
  xlsx = {
    color = "#207245",
    cterm_color = "29",
    icon = "󰈛",
    name = "Xlsx",
  },
  xm = {
    color = "#519aba",
    cterm_color = "74",
    icon = "",
    name = "Logos",
  },
  xml = {
    color = "#e37933",
    cterm_color = "166",
    icon = "󰗀",
    name = "Xml",
  },
  xmobarrc = {
    color = "#fd4d5d",
    cterm_color = "203",
    icon = "",
    name = "xmonad",
  },
  ["xmobarrc.hs"] = {
    color = "#fd4d5d",
    cterm_color = "203",
    icon = "",
    name = "xmonad",
  },
  xmonad = {
    color = "#fd4d5d",
    cterm_color = "203",
    icon = "",
    name = "xmonad",
  },
  ["xmonad.hs"] = {
    color = "#fd4d5d",
    cterm_color = "203",
    icon = "",
    name = "xmonad",
  },
  ["xorg.conf"] = {
    color = "#e54d18",
    cterm_color = "196",
    icon = "",
    name = "XorgConf",
  },
  xpi = {
    color = "#ff1b01",
    cterm_color = "196",
    icon = "",
    name = "Xpi",
  },
  ["xsettingsd.conf"] = {
    color = "#e54d18",
    cterm_color = "196",
    icon = "",
    name = "XSettingsdConf",
  },
  xul = {
    color = "#e37933",
    cterm_color = "166",
    icon = "",
    name = "Xul",
  },
  xz = {
    color = "#eca517",
    cterm_color = "214",
    icon = "",
    name = "Xz",
  },
  yaml = {
    color = "#6d8086",
    cterm_color = "66",
    icon = "",
    name = "Yaml",
  },
  yml = {
    color = "#6d8086",
    cterm_color = "66",
    icon = "",
    name = "Yml",
  },
  zig = {
    color = "#f69a1b",
    cterm_color = "172",
    icon = "",
    name = "Zig",
  },
  zip = {
    color = "#eca517",
    cterm_color = "214",
    icon = "",
    name = "Zip",
  },
  zorin = {
    color = "#14a1e8",
    cterm_color = "39",
    icon = "",
    name = "Zorin",
  },
  zsh = {
    color = "#89e051",
    cterm_color = "113",
    icon = "",
    name = "Zsh",
  },
  zst = {
    color = "#eca517",
    cterm_color = "214",
    icon = "",
    name = "Zst",
  },
  ["🔥"] = {
    color = "#ff4c1f",
    cterm_color = "196",
    icon = "",
    name = "Mojo",
  },
}
