set -g @tmux-gruvbox 'light'
set -g @tmux-gruvbox-statusbar-alpha 'true'

set -g status-position bottom
setw -g pane-border-format ""  # Nội dung rỗng
setw -g pane-border-lines single

setw -g pane-border-status bottom

