# Prompts
# set -g @mode_indicator_prefix_prompt ' 󰌌  '
# set -g @mode_indicator_copy_prompt ' 󰆏  '
# set -g @mode_indicator_sync_prompt ' 󰓦  '
# set -g @mode_indicator_empty_prompt '   '

set -g @mode_indicator_prefix_prompt ' PREF '
set -g @mode_indicator_copy_prompt ' YANK '
set -g @mode_indicator_sync_prompt ' SYNC '
set -g @mode_indicator_empty_prompt ' TMUX '

# Styles (Catppuccin Mocha Palette)
set -g @mode_indicator_prefix_mode_style 'bg=#f38ba8,fg=#11111b,bold'
set -g @mode_indicator_copy_mode_style 'bg=#f9e2af,fg=#11111b,bold'
set -g @mode_indicator_sync_mode_style 'bg=#f38ba8,fg=#11111b,bold'
set -g @mode_indicator_empty_mode_style 'bg=#94e2d5,fg=#11111b,bold'
