return {
  -- -- 1. NVIM-NAVIC (DEPENDENCY BẮT BUỘC)
  -- {
  --   "SmiteshP/nvim-navic",
  --   lazy = false, -- Nên load sớm
  --   -- navic KHÔNG cần setup, nó sẽ được attach trong on_attach của LSP.
  -- },
  --
  -- -- 2. BARBECUE (WINBAR CHÍNH)
  -- {
  --   "utilyre/barbecue.nvim",
  --   -- Barbecue cần Navic để hiển thị ngữ cảnh code
  --   dependencies = {
  --     "SmiteshP/nvim-navic",
  --     "nvim-tree/nvim-web-devicons", -- Cần để hiển thị icon đẹp
  --   },
  --   event = "BufReadPost", -- Chỉ load khi mở file (tiết kiệm thời gian khởi động)
  --
  --   opts = {
  --     -- attach_navic = false,
  --
  --     -- Tùy chọn theme (màu sắc)
  --     theme = {},
  --   },
  -- },
}
