# Session Management Plugins
set -g @plugin 'omerxx/tmux-floax'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tmux-continuum"

# Status Bar Plugins
set -g @plugin 'tmux-plugins/tmux-online-status'
set -g @plugin 'tmux-plugins/tmux-battery'

# Theme Plugin
# set -g @plugin 'catppuccin/tmux'
# set -g @plugin "janoamaral/tokyo-night-tmux"
# set -g @plugin "arcticicestudio/nord-tmux"
# set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'rose-pine/tmux-rosepine'

# tmux-opencode-session-manager
set -g @plugin 'githubcuaan/tmux-opencode-session-manager'
