# Run Opencode in a separate session
bind t run-shell '\
  PATH_HASH=$(echo "#{pane_current_path}" | md5sum | cut -c1-8); \
  SESSION="opencode-${PATH_HASH}"; \
  PORT=$((16#${PATH_HASH:0:4} % 55536 + 10000)); \
  tmux new-session -d -s "$SESSION" -c "#{pane_current_path}" "opencode --port $PORT"; \
  tmux display-popup -w 90% -h 85% -E "tmux attach-session -t $SESSION"'

bind -r h display-popup -d "#{pane_current_path}" -w 90% -h 90% -E "hunk diff"

bind-key C-t display-popup -d "#{pane_current_path}" -w 80% -h 80% -E "zsh"
bind-key C-g display-popup -d "#{pane-current-path}" -w 90% -h 90% -E "lazygit"
