bind -r h display-popup -d "#{pane_current_path}" -w 90% -h 90% -E "hunk diff"
bind-key C-t display-popup -d "#{pane_current_path}" -w 80% -h 80% -E "zsh"
bind-key C-b display-popup -d "#{pane_current_path}" -w 80% -h 80% -E "but tui"
